### ISSUE TITLE
Caching not turning off when debug is set

### ISSUE THREAD

**Issue by Webslung** [MizzouCreative/mizzoumvc#3]
When WP_DEBUG is set to false in WP_CONFIG caching doesn't turn off.

Jeremiah found the line of code where it is set. See string below:

> Line 64 of library/ViewEngineLoader.php: `'cache'         => $this->_determineViewCacheLocation(),`
> 
> However, there's also this: `$boolAutoReload = (defined('WP_DEBUG')) ? WP_DEBUG : false;`
> 
> Which is used on line 65: `'auto_reload'   => $boolAutoReload,` so I believe that's _supposed_ to govern caching with WP_DEBUG, but Twig must not function quite how we're thinking it does.
> 
> For the moment... I think if you just set "caching" to false, it will stop caching.

I can confirm the following change worked for me in the interim for local development:

change

```$this->_determineViewCacheLocation()```

to
 
 ```false```

**Comment by gilzow** [comment]
Implemented MIZZOUMVC_DISABLE_VIEW_CACHE to fully disable caching in v3.6.3
